### ISSUE TITLE
Bindonce Problems

### ISSUE THREAD

**Issue by RobinThrift** [sofa/angular-sofa-footer-links#1]
Bindonce 0.3.1 doesn't work with angular 1.3. The problem has been fixed in 0.3.3 but that version has not yet been published to npm: Pasvaz/bindonce#117

Should we just replace it with angular 1.3 one time bindings?
@PascalPrecht

**Comment by 0x-r4bbit** [comment]
Yes that's part of the migration process once all components are sliced. Please use one-time bindings in that component already.

**Comment by RobinThrift** [comment]
Okay, thanks.
